export const networkUrls = {
  addCountry: "/country/add-country",
  editCountry: "/country/edit-country",
  deleteCountry: "/country/delete-country",
  getAllCountry: "/country/get-all-countries",
  addState: "/state/add-state",
  deleteState: "/state/delete-state",
  editState: "/state/edit-state",
  getAllStates: "/state/all-states",
  addCity: "/city/create-city",
  editCity: "/city/edit-city",
  deleteCity: "/city/delete-city",
  getAllCitys: "/city/get-all-cities",
  addCategory: "/category/add-category",
  editCategory: "/category/edit-category",
  deleteCategory: "/category/delete-category",
  getCategory: "/category/get-all-category",
  addSubCategory: "/subcategory/add-sub-category",
  updateSubCategory: "/subcategory/edit-sub-category",
  deleteSubCategory: "/subcategory/delete-sub-category",
  getSubCategories: "/subcategory/get-all-sub-categories",
};
